language: python
python:
  - '3.7-dev'
install:
  - 'pip install pipenv'
  - 'pipenv lock'
  - 'pipenv sync'
before_script:
  - './manage.py makemigrations'
  - './manage.py migrate'
script:
  - './manage.py test'